# Numpy

The NumPy library is the core library for scientific computing in Python. It provides a high-performance multidimensional array object and tools for working with these arrays.


## Convetional way to import numpy:

> import numpy as np

***

### Creating numpy arrays

In [1]:
import numpy as np
li = [1,2,3]
a = np.array(li)
print("Single Dimension: ",a, type(a),"\n")

b = np.array([(1.5,2,3), (4,5,6)], dtype = float)
print("Two Dimension: \n",b,"\n")

c = np.array([[(1.5,2,3), (4,5,6)], [(3,2,1), (4,5,6)]],dtype = float)
print("Three dimension:\n",c)

Single Dimension:  [1 2 3] <class 'numpy.ndarray'> 

Two Dimension: 
 [[1.5 2.  3. ]
 [4.  5.  6. ]] 

Three dimension:
 [[[1.5 2.  3. ]
  [4.  5.  6. ]]

 [[3.  2.  1. ]
  [4.  5.  6. ]]]


### Initial placeholders

In [2]:
# Create an array of zeros
arr_zero = np.zeros((2,2), dtype = int)
print(arr_zero,"\n")

# Create an array of ones
arr_one = np.ones((2,3))
print(arr_one,"\n")

# Create an array of constant
arr_const = np.full((2,2),7)
print(arr_const,"\n")

# Create an array of evenly spaced values with step
arr_range = np.arange(10,30,5)
print(arr_range,"\n")

# Create an array of evenly spaced values with number of elements
arr_range_2 = np.linspace(0,2,9)
print(arr_range_2,"\n")

# Create a identity matrix
arr_identity = np.eye(2)
print(arr_identity,"\n")

# Create an empty array
arr_emp = np.empty((3,4))
print(arr_emp)

[[0 0]
 [0 0]] 

[[1. 1. 1.]
 [1. 1. 1.]] 

[[7 7]
 [7 7]] 

[10 15 20 25] 

[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ] 

[[1. 0.]
 [0. 1.]] 

[[1.5 2.  3.  4. ]
 [5.  6.  3.  2. ]
 [1.  4.  5.  6. ]]


### I/O

### Saving & Loading on Disk

In [22]:
# Initialize array
np_array = np.zeros((2,3))

# saves to file
np.save("file_name",np_array)

# saves as zip file
np.savez("file_name2",np_array)

# Load from disk
np_array_2 = np.load("file_name.npy")

print(np_array_2)

[[0. 0. 0.]
 [0. 0. 0.]]


### Saving & Loading text files

In [26]:
# Initialize array
np_array = np.zeros((2,3))


np.savetxt("myarray.txt",np_array,delimiter = " ")
arr1 = np.loadtxt("myarray.txt")
print(arr1)

np.savetxt("myarray.csv",np_array,delimiter = ",")
arr2 = np.genfromtxt("myarray.csv", delimiter = ',')
print(arr2)

[[0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]]


### Inspecting Numpy Arrays

In [38]:
# Initialize array
array = np.ones((2,3))
print(array)

# Array dimension
print("Dimension: ", array.shape)

# Length of array
print("Length of Array: ", len(array))

# Number of array dimensions:
print("Number of array dimensions:", array.ndim)

# Number of array elements:
print("Number of array elements: ",array.size)

# Datatype of array elements:
print(array.dtype)

[[1. 1. 1.]
 [1. 1. 1.]]
Dimension:  (2, 3)
Length of Array:  2
Number of array dimensions: 2
Number of array elements:  6
float64


### Arithmetic Operations

In [47]:
a = np.array([[1,2,3],[1,1,1]])
b = np.array([[1,2,3],[1,0,0]])

# Substraction
sub = a-b
print(sub)

# Addition
add = a+b
print(add)

# same for Multiplication and Divion

# Exponentiation
e = np.exp(a)
print(e)

# Sqaure root
sq = np.sqrt(a)
print(sq)


print(np.sin(a))
print(np.log(a))

# dot for matrix dot multiplication
# .T for transpose of matrix
dot = a.dot(b.T)
print(dot)

[[0 0 0]
 [0 1 1]]
[[2 4 6]
 [2 1 1]]
[[ 2.71828183  7.3890561  20.08553692]
 [ 2.71828183  2.71828183  2.71828183]]
[[1.         1.41421356 1.73205081]
 [1.         1.         1.        ]]
[[0.84147098 0.90929743 0.14112001]
 [0.84147098 0.84147098 0.84147098]]
[[0.         0.69314718 1.09861229]
 [0.         0.         0.        ]]
[[14  1]
 [ 6  1]]


### Comparisons

In [53]:
a = np.array([[1,2,3],[1,1,1]])
b = np.array([[1,2,3],[1,0,0]])

# Comaprison with other array
print(a==b)

# Comparison with constant
print(a<2)

# Array-wise comparison
print(np.array_equal(a,b))

[[ True  True  True]
 [ True False False]]
[[ True False False]
 [ True  True  True]]
False


### Aggregate Function

In [2]:
a = np.array([[1,2,3],[1,1,1]])

# Array-wise sum
print(a.sum())

# Minimum value (or maximum value with max())
print(a.min())

# Maximum value in a row
print(a.max(axis = 0))

9
1
[1 2 3]


In [21]:
a = np.array([[1,2,3],[3,5,6]])

# Mean
print(a.mean())

# Median
print(np.median(a))

# Correlation Coefficient
print(np.corrcoef(a))

print(np.std(a))

3.3333333333333335
3.0
[[1.         0.98198051]
 [0.98198051 1.        ]]
1.699673171197595


### Copy an array

In [30]:
a = np.array([[1,2,3],[3,5,6]])

b = a
b+=2

print('a = ',a,"\n",'b = ',b)

c = np.copy(a)
c+=5

d = a.copy()
d-=3

print('a = ',a,"\n",'c =',c,"d = ",d)


a =  [[3 4 5]
 [5 7 8]] 
 b =  [[3 4 5]
 [5 7 8]]
a =  [[3 4 5]
 [5 7 8]] 
 c = [[ 8  9 10]
 [10 12 13]] d =  [[0 1 2]
 [2 4 5]]


### Indexing & Slicing 

In [35]:
#Single dimension
a = np.array([0,1,2,3])
print(a[2])

# Two dimension
a = np.array([[1,2,3],[4,5,6]])
print(a[0,2])


2
3


In [7]:
a = np.array([[1,2,3],[4,5,6],[4,56,67]])
#a = np.array([1,2,3])
# print everything
print(a[:,:],"\n")

# print first element of all sub-arrays
print(a[:,0],"\n")

#print array in reverse order
print(a[::-1])

[[ 1  2  3]
 [ 4  5  6]
 [ 4 56 67]] 

[1 4 4] 

[[ 4 56 67]
 [ 4  5  6]
 [ 1  2  3]]


In [3]:
a = np.array([[1,2,3],[4,5,6],[4,56,67]])
a = a.reshape(9)
print(a)
a = a.reshape(3,3)
print(a)


[ 1  2  3  4  5  6  4 56 67]
[[ 1  2  3]
 [ 4  5  6]
 [ 4 56 67]]


### Array Manipulation

In [4]:
a = np.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [5]:
# Transpose
print(a.T)

[[1 4]
 [2 5]
 [3 6]]


In [49]:
# Change array shape

# Flatten the array
print(a.ravel(), "\n")

# Reshape
print(a.reshape(1,1,6))

[1 2 3 4 5 6] 

[[[1 2 3 4 5 6]]]


In [6]:
#Adding/removing elements
a = np.array([[1,2,3],[4,5,6]])
b = [[1,1,1],[1,2,3]]
a = np.append(a,b)
print(a)


# Insert at location
a = np.insert(a,6,5)
print(a)


# Delete items
a = np.delete(a,[1])
print(a)

[1 2 3 4 5 6 1 1 1 1 2 3]
[1 2 3 4 5 6 5 1 1 1 1 2 3]
[1 3 4 5 6 5 1 1 1 1 2 3]


### Combining & Splitting Arrays

In [5]:
import numpy as np
# Concatenate arrays
a = np.array([1,2,3])
d = np.array([10,15,20])

op = np.concatenate((a,d),axis=0) 
print(op)
'''OUTPUT:
array([ 1,  2,  3, 10, 15, 20])
'''

c = np.array([[1,2,3],
    [4,5,6]])

# Split the array vertically at the 2nd index    
op2 = np.vsplit(c,2)              
print(op2)


[ 1  2  3 10 15 20]
[array([[1, 2, 3]]), array([[4, 5, 6]])]
